### ISSUE TITLE
[cndsteroids] Index 1 not found

### ISSUE THREAD

**Issue by kempy007** [pastaCLS/cndsteroids#1]
Not sure whats up but unable to use your plugin in 32bit x96dbg.

First chance exception on 00201C05 (C0000096, EXCEPTION_PRIV_INSTRUCTION)!
BreakLogEAX is "PETERPAN{}"
[cndsteroids] Index 8 not found
00000000
[cndsteroids] PETERPAN{ was saved
[cndsteroids] Index 8 not found
00000000
[cndsteroids] Index 1 not found
00000000
[cndsteroids] PETERPAN{ was saved
[cndsteroids] Index 1 not found
00000000
[cndsteroids] Index 1 not found
00000000
[cndsteroids] Index 1 not found
00000000
[cndsteroids] Index 1 not found
00000000
[cndsteroids] PETERPAN{ is being remove
[cndsteroids] PETERPAN{ is being remove
[cndsteroids] PETERPAN{ was saved
Invalid value: "cndsteroids"!
Unknown command/expression: "cndsteroids"
[cndsteroids] Index 1 not found
00000000
[cndsteroids] Index 1 not found
00000000
Unknown command/expression: "cndsteroids.ismystring(, $UNICODE, 1)"
Invalid value: "stack"!
Unknown command/expression: "cndsteroids.ismystring(stack, $UNICODE, 1)"
[cndsteroids] Index 1 not found
00000000
Unknown command/expression: "cndsteroids.ismystring(eax, $UNICODE)"
Unknown command/expression: "cndsteroids.ismystring(eax, $ANSI)"
[cndsteroids] Index 1 not found
00000000
[cndsteroids] Index 8 not found
00000000

**Comment by pastaoficial** [comment]
Are you trying to break when EAX points to the string "PETERPAN{"?

in the previous log the call to ismystring was wrong, you need as 3rd argument the number of the string setted with setString

for example: setString 1,"Hi" and later use cndsteroids.ismystring(eax, $UNICODE, **1**)

if this doesn't work please let me know
