### ISSUE TITLE
[cndsteroids] Index 8 not found

### ISSUE THREAD

**Issue by marek5816** [pastaCLS/cndsteroids#2]
I having problem that was mentioned here, but I do not found any solution.

I am trying to use plugin be setting the string by **setString 8, "TestString"** and I got 

> [cndsteroids] TestString was saved

 but after using **cndsteroids.ismystring(esp, $ANSI, 8)** I got error 

> [cndsteroids] Index 8 not found
> 00000000

I am using latest build **snapshot_2019-04-22_11-53** and I was also trying download older build **snapshot_2017-02-28_05-09** but I am still getting same error.
Any solution?

**Comment by pastaoficial** [comment]
Hi @marek5816, I didn't update the code and is probably that any api was changed

esp has a pointer to "TestString", right?

**Comment by marek5816** [comment]
Hi @pastaCLS, yea, esp point to "TestString". I was trying to use example from ReadeMe. Do you have some clue in what version it should work?

**Comment by pastaoficial** [comment]
When the plugin was released, the x32dbg was [this version](https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2017-02-28_05-09.zip/download)

In the next days I will try to update the plugin in order to work with the last version

sorry for the troubles

**Comment by pastaoficial** [comment]
I probed the plugin with the last version and works well

maybe you set a pointer to the string in esp intead of the string

![image](https://user-images.githubusercontent.com/18431519/56758813-e5711380-676d-11e9-80c4-9794ef80b958.png)

you need to see the string in esp like this:

![image](https://user-images.githubusercontent.com/18431519/56758910-105b6780-676e-11e9-9d9c-96b581c153ba.png)

**Comment by marek5816** [comment]
I was trying it again right now and I make mistake. I had it in UNICODE, but even when I set second parameter $UNICODE it was not working,

**Comment by marek5816** [comment]
I was trying it in UNICODE but it was not working. I trying it again right now and it working, I must make somewhere mistake, I do not know where. Sorry for the time lost by solving this problem

**Comment by pastaoficial** [comment]
![image](https://user-images.githubusercontent.com/18431519/56759461-62e95380-676f-11e9-95e1-abadfb422378.png)

may be you forgot the double NULL at the end

![image](https://user-images.githubusercontent.com/18431519/56759496-772d5080-676f-11e9-82f0-1c966cc8ec8e.png)

**Comment by pastaoficial** [comment]
dont worry @marek5816, I'm happy to assisted you
